Repository solspace/craft-freeform, pull requests merged in 2023-08, with the labels that each got.

#763 [SFT-522][WIP]: Update Mailchimp Email Marketing
  packages/plugin/src/Attributes/EventListener.php
  packages/plugin/src/Bundles/Integrations/CRM/CrmBundle.php
  packages/plugin/src/Bundles/Integrations/CRM/Salesforce/SalesforceArrayValueProcessor.php
  packages/plugin/src/Bundles/Integrations/CRM/Salesforce/SalesforceTokenListener.php
  packages/plugin/src/Bundles/Integrations/CRM/Zoho/ZohoTokenListener.php
  packages/plugin/src/Bundles/Integrations/OAuth/OAuth2Bundle.php
  packages/plugin/src/Bundles/Integrations/OAuth/OAuth2RefreshTokenBundle.php
  packages/plugin/src/Bundles/Integrations/OAuth/RefreshedTokenPersistence.php
  packages/plugin/src/Bundles/Integrations/Providers/IntegrationClientProvider.php
  packages/plugin/src/Events/Integrations/GetAuthorizedClientEvent.php
  packages/plugin/src/Events/Integrations/OAuth2/FetchTokenEvent.php
  packages/plugin/src/Events/Integrations/OAuth2/InitiateAuthenticationFlowEvent.php
  packages/plugin/src/Events/Integrations/OAuth2/TokenPayloadEvent.php
  packages/plugin/src/Events/Integrations/RegisterIntegrationTypesEvent.php
  packages/plugin/src/Events/Integrations/SaveEvent.php
  packages/plugin/src/Integrations/CRM/ActiveCampaign/ActiveCampaign.php
  packages/plugin/src/Integrations/CRM/Freshdesk/Freshdesk.php
  packages/plugin/src/Integrations/CRM/HubSpot/HubSpot.php
  packages/plugin/src/Integrations/CRM/Infusionsoft/Infusionsoft.php
  packages/plugin/src/Integrations/CRM/Insightly/Insightly.php
  packages/plugin/src/Integrations/CRM/Pardot/PardotV5.php
  packages/plugin/src/Integrations/CRM/Pipedrive/BasePipedriveIntegration.php
  packages/plugin/src/Integrations/CRM/Pipedrive/Versions/PipedriveV1.php
  packages/plugin/src/Integrations/CRM/Salesforce/BaseSalesforceIntegration.php
  packages/plugin/src/Integrations/CRM/Salesforce/SalesforceIntegrationInterface.php
  packages/plugin/src/Integrations/CRM/Salesforce/Versions/SalesforceV58.php
  packages/plugin/src/Integrations/CRM/SharpSpring/SharpSpring.php
  packages/plugin/src/Integrations/CRM/Zoho/BaseZohoIntegration.php
  packages/plugin/src/Integrations/CRM/Zoho/Versions/BaseZohoV2Integration.php
  packages/plugin/src/Integrations/CRM/Zoho/Versions/ZohoV2.php
  packages/plugin/src/Integrations/CRM/Zoho/ZohoIntegrationInterface.php
  packages/plugin/src/Integrations/MailingLists/ActiveCampaign/ActiveCampaign.php
  packages/plugin/src/Integrations/MailingLists/Campaign/Campaign.php
  packages/plugin/src/Integrations/MailingLists/CampaignMonitor/CampaignMonitor.php
  packages/plugin/src/Integrations/MailingLists/ConstantContact/ConstantContact3.php
  packages/plugin/src/Integrations/MailingLists/Dotmailer/Dotmailer.php
  packages/plugin/src/Integrations/MailingLists/MailChimp/MailChimp.php
  packages/plugin/src/Library/Integrations/APIIntegrationInterface.php
  packages/plugin/src/Library/Integrations/BaseIntegration.php
  packages/plugin/src/Library/Integrations/OAuth/OAuth2ConnectorInterface.php
  packages/plugin/src/Library/Integrations/OAuth/OAuth2RefreshTokenInterface.php
  packages/plugin/src/Library/Integrations/OAuth/OAuth2RefreshTokenTrait.php
  packages/plugin/src/Library/Integrations/OAuth/OAuth2Trait.php
  packages/plugin/src/Library/Integrations/OAuth/RefreshTokenInterface.php
  packages/plugin/src/Library/Integrations/Types/CRM/CRMIntegrationInterface.php
  packages/plugin/src/Library/Integrations/Types/CRM/CRMOAuthConnector.php
  packages/plugin/src/Library/Integrations/Types/MailingLists/MailingListOAuthConnector.php
  packages/plugin/src/Services/Integrations/AbstractIntegrationService.php
  packages/plugin/src/Services/Integrations/CrmService.php
  packages/plugin/src/Services/Integrations/IntegrationsService.php
  packages/plugin/src/controllers/integrations/IntegrationsController.php
  packages/plugin/src/controllers/integrations/OAuthController.php
Labels: refactor

#776 [SFT-551]: Restyle custom dropdown
  packages/client/src/app/components/elements/custom-dropdown/check.svg
  packages/client/src/app/components/elements/custom-dropdown/close.svg
  packages/client/src/app/components/elements/custom-dropdown/dropdown.options.styles.ts
  packages/client/src/app/components/elements/custom-dropdown/dropdown.options.tsx
  packages/client/src/app/components/elements/custom-dropdown/dropdown.styles.ts
  packages/client/src/app/components/elements/custom-dropdown/dropdown.tsx
  packages/client/src/app/pages/forms/edit/builder/tabs/rules/conditions/table/field/field.tsx
  packages/client/src/app/pages/forms/edit/builder/tabs/rules/conditions/table/field/group-field.svg
  packages/client/src/app/pages/forms/edit/store/index.ts
  packages/client/src/app/pages/forms/edit/store/slices/layout/layouts/layouts.selectors.ts
  packages/client/src/styles/variables.ts
  packages/client/src/types/properties.ts
  packages/plugin/src/Integrations/MailingLists/Campaign/BaseCampaignIntegration.php
  packages/plugin/src/Resources/js/client/client.js
Labels: feature

#786 [SFT-530]: Switch form, integration, and field name generators to just be simple, e.g. Form 1, Form 2, Textarea 1, Textarea 2, etc
  packages/client/src/app/pages/forms/edit/builder/tabs/notifications/property-editor/property-editor.styles.ts
  packages/client/src/app/pages/forms/edit/store/slices/layout/fields/index.ts
  packages/client/src/app/pages/forms/edit/store/slices/notifications/notifications.selectors.ts
  packages/client/src/app/pages/forms/edit/store/thunks/notifications.ts
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
Labels: feature

#785 [SFT-495]: Bring in reCAPTCHA/hCaptcha to Integrations builder tab
  packages/plugin/src/Bundles/Integrations/Providers/FormIntegrationsProvider.php
  packages/plugin/src/Integrations/Captchas/ReCaptcha/ReCaptcha.php
  packages/plugin/src/Integrations/Captchas/hCaptcha/hCaptcha.php
  packages/plugin/src/Library/Integrations/EnabledByDefault/EnabledByDefaultInterface.php
  packages/plugin/src/Library/Integrations/EnabledByDefault/EnabledByDefaultTrait.php
  packages/plugin/src/Library/Integrations/Types/Captchas/CaptchaIntegrationInterface.php
Labels: feature

#790 [v4] [SFT-576] - Not all Stripe validation errors are accounted for and cause the form to break
  packages/plugin/src/Services/Pro/Payments/StripeService.php
Labels: issue, bug, fix

#792 [v5] [SFT-576] - Not all Stripe validation errors are accounted for and cause the form to break
  packages/plugin/src/Services/Pro/Payments/StripeService.php
Labels: issue, bug, fix

#808 [SFT-583]: Forms ALWAYS seem to submit as AJAX no matter if the AJAX setting is enabled or not
  packages/plugin/src/Resources/js/scripts/cp/integrations/edit.js
  packages/plugin/src/Resources/js/scripts/front-end/captchas/hcaptcha/checkbox.js
  packages/plugin/src/Resources/js/scripts/front-end/captchas/hcaptcha/invisible.js
  packages/plugin/src/Resources/js/scripts/front-end/captchas/recaptcha/v2-checkbox.js
  packages/plugin/src/Resources/js/scripts/front-end/captchas/recaptcha/v2-invisible.js
  packages/plugin/src/Resources/js/scripts/front-end/captchas/recaptcha/v3.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js.LICENSE.txt
  packages/scripts/.babelrc.json
  packages/scripts/src/components/front-end/captchas/recaptcha/v2-invisible.ts
  packages/scripts/src/components/front-end/plugin/freeform.js
  packages/scripts/src/lib/plugin/handlers/fields/drag-and-drop/file-upload.ts
  packages/scripts/src/lib/plugin/handlers/form/stripe-handler.js
  packages/scripts/tsconfig.json
  packages/scripts/webpack.config.js
Labels: fix

#815 chore - Removed refresh button from Dynamic Select control type
  packages/client/src/app/components/form-controls/control-types/dynamic-select/dynamic-select.styles.ts
  packages/client/src/app/components/form-controls/control-types/dynamic-select/dynamic-select.tsx
  packages/client/src/app/components/form-controls/control-types/dynamic-select/icons/refresh.svg
  packages/plugin/src/Resources/js/client/client.js
Labels: issue

#814 [SFT-570] - Field button names (left column in Layout) in form builder are being clipped off 1-2px at bottom
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-list/field-group/field/field.styles.tsx
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
Labels: fix

#817 [SFT-562] - Notifications tab inside builder will show loading state forever when there are no notifications configured
  packages/client/src/app/pages/forms/edit/builder/tabs/notifications/property-editor/empty-editor.tsx
  packages/plugin/src/Resources/js/client/client.js
Labels: fix

#812 [SFT-569] - Can we update any references to 'Select' in Table fields …
  packages/plugin/src/Fields/Implementations/Pro/TableField.php
  packages/plugin/src/Library/Attributes/TableAttributesCollection.php
  packages/plugin/src/templates/_defaultFormTemplates/bootstrap-5-dark/fields/table.twig
  packages/plugin/src/templates/_defaultFormTemplates/bootstrap-5-floating-labels/fields/table.twig
  packages/plugin/src/templates/_defaultFormTemplates/bootstrap-5/fields/table.twig
  packages/plugin/src/templates/_defaultFormTemplates/foundation-6/fields/table.twig
  packages/plugin/src/templates/_defaultFormTemplates/tailwind-3/fields/table.twig
  packages/plugin/tests/Unit/Attributes/Property/PropertyTypes/Table/TableTransformerTest.php
Labels: fix
