Repository solspace/craft-freeform, pull requests merged in 2024-05, with the labels that each got.

#1250 fix(SFT-1081): Set integration model properties after EVENT_BEFORE_SAVE
  packages/plugin/src/Services/Integrations/IntegrationsService.php
Labels: fix

#1249 fix(SFT-1035): Prevent Notification Persistence throwing errors if the form upsert event has errors.
  packages/plugin/src/Bundles/Persistence/NotificationPersistence.php
Labels: fix

#1255 [#1224]: Improving twig template debugging for formatting templates
  packages/plugin/src/Services/FilesService.php
  packages/plugin/src/Services/FormsService.php
Labels: refactor

#1257 feat(SFT-1073): Added Assets as an Element source for populating Freeform fields
  packages/plugin/src/Bundles/Routing/routes/cp/elements/elements.php
  packages/plugin/src/Fields/Properties/Options/Elements/Types/Assets/Assets.php
  packages/plugin/src/controllers/api/elements/AssetController.php
  packages/plugin/src/controllers/api/types/OptionsController.php
Labels: feature

#1261 fix(SFT-1090): Run form limits after the form has rendered
  packages/plugin/src/Bundles/Form/Limiting/FormLimiting.php
Labels: fix, freeform5

#1260 fix(SFT-1089): Improved field association badges for Checkbox, HTML and Rich Text fields in Form Builder
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/field/cell/cell.styles.ts
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/field/cell/cell.tsx
  packages/plugin/src/Fields/Implementations/CheckboxField.php
  packages/plugin/src/Fields/Interfaces/NoLabelInterface.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
  packages/plugin/src/Resources/js/client/vendor.js.LICENSE.txt
Labels: fix, freeform5

#1262 [SFT-1093]: Update feed
  packages/client/src/app/components/form-controls/control-types/options/options.tsx
  packages/plugin/src/Bundles/Feed/FeedBundle.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Services/FreeformFeedService.php
Labels: fix

#1267 fix(SFT-1094): Make sure Origins is in the expected format (FF5)
  packages/plugin/src/controllers/SubmitController.php
Labels: fix

#1266 fix(SFT-1094): Make sure Origins is in the expected format (FF4)
  packages/plugin/src/Controllers/SubmitController.php
Labels: fix

#1265 [SFT-1067]: Integration error log improvement
  packages/plugin/src/Library/Integrations/BaseIntegration.php
Labels: feature

#1264 [SFT-1087]: Default Status management
  composer.json
  packages/plugin/src/Freeform.php
  packages/plugin/src/Models/StatusModel.php
  packages/plugin/src/Services/StatusesService.php
  packages/plugin/src/Services/SubmissionsService.php
  packages/plugin/src/controllers/StatusesController.php
  packages/plugin/src/migrations/Install.php
  packages/plugin/src/migrations/m240507_073204_DropStatusDefaultColumn.php
  packages/plugin/src/templates/statuses/edit.twig
  packages/plugin/src/templates/statuses/index.twig
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature

#1228 fix(SFT-1055): The 'per event' ALL DAY field mapping for Freeform submissions to Calendar (FF3)
  packages/plugin/src/Library/Connections/CalendarEvents.php
  packages/plugin/src/Library/Connections/Transformers/AbstractFieldTransformer.php
  packages/plugin/src/Library/Connections/Transformers/CheckboxTransformer.php
Labels: fix

#1276 [SFT-869]: Google Sheets integration
  packages/client/src/app/components/form-controls/control-types/dynamic-select/dynamic-select.tsx
  packages/client/src/app/components/form-controls/control-types/namespaced/field-mapping/mapping.tsx
  packages/plugin/src/Bundles/Integrations/Providers/FormIntegrationsProvider.php
  packages/plugin/src/Integrations/Captchas/ReCaptcha/ReCaptchaBundle.php
  packages/plugin/src/Integrations/Captchas/hCaptcha/hCaptchaBundle.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/BaseGoogleSheetsIntegration.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/Controllers/GoogleSheetsController.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/EventListeners/GoogleSheetsTokenListener.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/EventListeners/RegisterControllers.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/GoogleSheetsBundle.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/GoogleSheetsIntegrationInterface.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/README.md
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/Utilities/SheetsHelper.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/Versions/GoogleSheetsV4.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/icon.svg
  packages/plugin/src/Integrations/Other/OtherIntegrationBundle.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/EventListeners/RegisterField.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Fields/StripeField.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/README.md
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Stripe.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Services/Integrations/IntegrationsService.php
  packages/plugin/src/Services/SettingsService.php
  packages/plugin/src/Tests/Integrations/Other/Google/GoogleSheets/Utilities/SheetsHelperTest.php
Labels: feature

#1289 [SFT-1138]: Express Forms migration utility crash
  packages/plugin/src/Bundles/Backup/Export/ExpressFormsExporter.php
Labels: fix

#1296 [SFT-1142]: Feeds table lookup crash on fresh install
  packages/plugin/src/Services/FreeformFeedService.php
Labels: fix

#1292 [SFT-1139]: Fetching payment records in Submissions query no longer possible since v5
  packages/plugin/src/Integrations/PaymentGateways/Common/PaymentFieldInterface.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/EventListeners/RenderNotifications.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Services/StripeCallbackService.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Services/StripePaymentService.php
  packages/plugin/src/Models/Payments/PaymentModel.php
  packages/plugin/src/Variables/FreeformVariable.php
Labels: fix

#1293 [SFT-1140]: Stripe using `window.onload()` when it should not
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
  packages/scripts/src/components/front-end/payments/stripe/elements.events.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.ts
Labels: fix

#1294 [SFT-1076]: Conditional Rules JS with Vue.js
  packages/plugin/src/Bundles/Rules/RulesBundle.php
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/plugin/src/templates/submissions/edit.twig
  packages/scripts/src/lib/plugin/handlers/form/rules.ts
Labels: fix

#1299 [SFT-1137][#1278]: Asset loading improvements
  packages/plugin/src/Events/Forms/RenderTagEvent.php
  packages/plugin/src/Freeform.php
  packages/plugin/src/Integrations/Captchas/ReCaptcha/ReCaptchaBundle.php
  packages/plugin/src/Integrations/Captchas/hCaptcha/hCaptchaBundle.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Controllers/StripeScriptsController.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/EventListeners/RegisterField.php
  packages/plugin/src/Library/Attributes/Attributes.php
  packages/plugin/src/Models/Settings.php
  packages/plugin/src/Services/FormsService.php
  packages/plugin/src/Services/SettingsService.php
  packages/plugin/src/Variables/FreeformVariable.php
  packages/plugin/src/controllers/BaseFilesProxyController.php
  packages/plugin/src/controllers/ResourcesController.php
  packages/plugin/src/templates/settings/_form-behavior.twig
  packages/plugin/src/templates/welcome/index.twig
Labels: fix

#1312 fix(SFT-1148): Printing surveys & polls report/results page as PDF
  packages/client/src/index.tsx
  packages/client/src/styles.css
  packages/plugin/src/Resources/js/client/client.js
Labels: fix, freeform5

#1310 fix(SFT-1149): Twig Template Loading Error - Unable to find the template 'freeform/C:\'
  packages/plugin/src/Services/FormsService.php
Labels: fix, freeform5

#1321 fix(SFT-1153): Allow en dash and em dash characters on save
  packages/plugin/src/Elements/Submission.php
Labels: fix, freeform5

#1322 fix(SFT-1153): Allow en dash and em dash characters on save
  packages/plugin/src/Elements/Submission.php
  packages/plugin/src/Services/DiagnosticsService.php
Labels: fix

#1323 fix(SFT-1143): Table field type respects all property editor settings
  packages/plugin/src/Bundles/Fields/Validation/TableValidation.php
  packages/plugin/src/Fields/Implementations/Pro/TableField.php
  packages/plugin/src/Fields/Interfaces/TableInterface.php
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/scripts/src/lib/plugin/handlers/fields/table.ts
Labels: fix, freeform5
