Repository solspace/craft-freeform, pull requests merged in 2024-03, with the labels that each got.

#1084 fix(SFT-911) Fill Form Values from the GET Query String
  packages/plugin/src/Bundles/Form/Context/Request/GetContext.php
Labels: fix

#1097 [SFT-932]: fixing page buttons not being translatable
  packages/plugin/src/Form/Layout/Page/Buttons/PageButtons.php
Labels: fix

#1100 [SFT-935]: Stripe Payment Element briefly shows error after submit and before success - possibly due to having 2 Stripe fields in same form?
  packages/plugin/src/Bundles/Fields/Validation/CalculationFieldValidation.php
  packages/plugin/src/Bundles/Rules/RulesInitialState.php
  packages/plugin/src/Fields/Implementations/Pro/CalculationField.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
  packages/plugin/src/Resources/js/client/vendor.js.LICENSE.txt
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
  packages/scripts/src/components/front-end/payments/stripe/elements.init.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.selectors.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.submit.ts
Labels: fix

#1107 [SFT-931]: Adding empty options support
  packages/client/src/app/components/form-controls/control-types/options/options.types.ts
  packages/client/src/app/components/form-controls/control-types/options/sources/configurable/configurable.tsx
  packages/client/src/app/components/options/use-field-options.ts
  packages/plugin/src/Fields/Properties/Options/OptionsConfiguration.php
  packages/plugin/src/Resources/js/client/client.js
Labels: feature

#1133 fix(SFT-958): Processing Dynamic Recipients
  packages/plugin/src/migrations/m230101_200000_FF4to5_MigrateData.php
Labels: bug, fix

#1134 fix(SFT-920) Migration fixes for skipped submissions tables
  packages/plugin/src/migrations/m230101_200000_FF4to5_MigrateData.php
Labels: fix

#1142 [SFT-965] - Page tabs become inaccessible when the number of tabs exceeds the width of the browser window.
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/page-tabs/page-tabs.styles.ts
  packages/plugin/src/Resources/js/client/client.js
Labels: fix

#1143 Addressing various bugs
  composer.json
  packages/client/src/app/components/form-controls/control-types/namespaced/notifications/recipients/recipients.tsx
  packages/plugin/src/Bundles/Form/Attributes/FormAttributesBundle.php
  packages/plugin/src/Bundles/Form/ElementEdit/ElementEditBundle.php
  packages/plugin/src/Bundles/Integrations/Elements/ValueTransformers/BooleanValueTransformer.php
  packages/plugin/src/Fields/Implementations/FileUploadField.php
  packages/plugin/src/Integrations/Elements/Entry/Entry.php
  packages/plugin/src/Integrations/Elements/User/EventListeners/PasswordTransform.php
  packages/plugin/src/Integrations/Elements/User/EventListeners/PhotoTransform.php
  packages/plugin/src/Integrations/Elements/User/User.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Fields/StripeField.php
  packages/plugin/src/Library/Integrations/Types/Elements/ElementIntegration.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Services/DiagnosticsService.php
  packages/plugin/src/controllers/api/elements/UserController.php
  packages/plugin/src/migrations/m240315_100655_UserIntegrationMultiGroupChoice.php
Labels: fix

#1154 [SFT-985]: fixing multiple stripe integration support
  packages/plugin/src/Integrations/PaymentGateways/Stripe/EventListeners/RegisterField.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Fields/StripeField.php
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/scripts/src/components/front-end/payments/stripe/elements.config.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.init.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.submit.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.ts
  packages/scripts/src/components/front-end/payments/stripe/elements.types.ts
  packages/scripts/src/lib/plugin/handlers/form/rules.ts
Labels: fix

#1155 [SFT-980]: Add "Not like" option in Export Profiles
  packages/plugin/src/Models/Pro/ExportProfileModel.php
  packages/plugin/src/templates/export/profiles/edit.twig
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature

#1156 Various fixes
  packages/client/src/app/pages/forms/edit/builder/tabs/rules/conditions/table/field/field.tsx
  packages/client/src/app/pages/forms/edit/builder/tabs/rules/editor/field-editor.tsx
  packages/client/src/app/pages/forms/edit/store/slices/rules/fields/field-rules.selectors.ts
  packages/client/src/hooks/use-click-outside.ts
  packages/plugin/src/Resources/js/client/client.js
Labels: fix

#1162 fix(SFT-990): Improved scrollbar styling for page tabs in Safari browser
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/page-tabs/page-tabs.styles.ts
  packages/client/src/styles/mixins.ts
  packages/plugin/src/Resources/js/client/client.js
Labels: fix

#1173 [SFT-1008]: The "Maximum Length" setting for Text fields
  packages/plugin/src/Bundles/Fields/Implementations/MaxLength/MaxLengthBundle.php
  packages/plugin/src/Bundles/Fields/Validation/MaxLengthValidation.php
  packages/plugin/src/Bundles/GraphQL/Types/Generators/FieldGenerator.php
  packages/plugin/src/Fields/Implementations/EmailField.php
  packages/plugin/src/Fields/Implementations/Pro/ConfirmationField.php
  packages/plugin/src/Fields/Implementations/Pro/DatetimeField.php
  packages/plugin/src/Fields/Implementations/TextField.php
  packages/plugin/src/Fields/Implementations/TextareaField.php
  packages/plugin/src/Fields/Interfaces/MaxLengthInterface.php
  packages/plugin/src/Fields/Traits/MaxLengthTrait.php
Labels: feature

#1174 [SFT-1006]: Broken tab label editor when scrollbar present
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/page-tabs/tab/tab.styles.ts
  packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-layout/page-tabs/tab/tab.tsx
  packages/client/src/app/pages/forms/edit/store/thunks/fields/remove.ts
  packages/plugin/src/Resources/js/client/client.js
Labels: fix

#1175 feat(SFT-555): Dotdigital Email Marketing Integration
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/BaseDotdigitalIntegration.php
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/DotdigitalBundle.php
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/DotdigitalIntegrationInterface.php
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/README.md
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/Versions/DotdigitalV2.php
  packages/plugin/src/Integrations/EmailMarketing/Dotdigital/icon.svg
Labels: feature
