Repository solspace/craft-freeform, pull requests merged in 2024-06, with the labels that each got.

#1328 fix(#1327): duplicate form listing in submissions/spam
  packages/plugin/src/Elements/Submission.php
Labels: fix

#1335 fix(SFT-1124): Reinstated CP submissions index chart
  CHANGELOG.md
  composer.json
  packages/plugin/src/Bundles/Routing/routes/cp/api.php
  packages/plugin/src/Resources/js/scripts/cp/submissions/element-index.js
  packages/plugin/src/Services/FormsService.php
  packages/plugin/src/controllers/api/SettingsController.php
  packages/scripts/src/components/cp/submissions/element-index.js
Labels: fix, freeform5

#1326 feat(SFT-1120): Added ability to set the default 'From Email' and 'From Name' values for new email notification templates
  packages/plugin/src/Models/Settings.php
  packages/plugin/src/Records/NotificationTemplateRecord.php
  packages/plugin/src/controllers/notifications/DatabaseController.php
  packages/plugin/src/controllers/notifications/FilesController.php
  packages/plugin/src/templates/_templates/email/default.twig
  packages/plugin/src/templates/settings/_template-manager.twig
  packages/plugin/src/translations/de/freeform.php
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature, freeform5

#1333 fix(SFT-1155): Uninstalling Freeform 5
  packages/plugin/src/Bundles/Migrations/RemoveForeignKeys.php
  packages/plugin/src/icon-mask.svg
  packages/plugin/src/icon.svg
Labels: fix, freeform5

#1336 feat(SFT-1159): Added modules to diagnostic page
  packages/plugin/src/Services/DiagnosticsService.php
  packages/plugin/src/controllers/DiagnosticsController.php
  packages/plugin/src/templates/settings/_diagnostics.twig
  packages/plugin/src/translations/de/freeform.php
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature, freeform5

#1339 [SFT-1152]: Elements integration issue on multi-site setup
  packages/plugin/src/Integrations/Elements/Entry/Entry.php
Labels: fix

#1350 [SFT-1165]: Inline styles and scripts, incompatible with Content Security Policy
  packages/plugin/src/Bundles/Fields/Implementations/RatingField/RatingFieldBundle.php
  packages/plugin/src/Events/Forms/RenderTagEvent.php
  packages/plugin/src/Fields/Implementations/Pro/RatingField.php
  packages/plugin/src/Integrations/PaymentGateways/Stripe/Fields/StripeField.php
  packages/plugin/src/Integrations/Single/JavascriptTest/EventListeners/JavascriptTestBundle.php
  packages/plugin/src/Integrations/Single/JavascriptTest/Scripts/js-test.js
  packages/plugin/src/Library/Helpers/FileHelper.php
  packages/plugin/src/Resources/css/front-end/fields/rating.css
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/plugin/src/Tests/Library/Helpers/FileHelperTest.php
  packages/scripts/src/components/front-end/payments/stripe/elements.config.ts
  packages/scripts/src/components/front-end/plugin/freeform.ts
  packages/scripts/src/lib/plugin/handlers/fields/rating.ts
  packages/styles/src/front-end/fields/rating.scss
Labels: feature

#1359 [refactor][SFT-302]: Spam Block move from project config to integrations
  composer.json
  package-lock.json
  packages/client/src/app/components/form-controls/control-types/textarea/textarea.styles.ts
  packages/client/src/app/components/form-controls/control-types/textarea/textarea.tsx
  packages/client/src/app/components/form-controls/control.tsx
  packages/client/src/app/components/form-controls/message-list.tsx
  packages/client/src/types/properties.ts
  packages/plugin/src/Attributes/Integration/Type.php
  packages/plugin/src/Attributes/Property/Message.php
  packages/plugin/src/Attributes/Property/Property.php
  packages/plugin/src/Attributes/Property/ValueTransformers/SeparatedStringToArrayTransformer.php
  packages/plugin/src/Bundles/Attributes/Property/PropertyProvider.php
  packages/plugin/src/Bundles/Form/SpamControl/Checks/BlacklistedEmails.php
  packages/plugin/src/Bundles/Form/SpamControl/Checks/BlacklistedIps.php
  packages/plugin/src/Bundles/Form/SpamControl/Checks/BlacklistedKeywords.php
  packages/plugin/src/Bundles/Integrations/Providers/IntegrationDTOProvider.php
  packages/plugin/src/Bundles/Persistence/IntegrationPersistence.php
  packages/plugin/src/Fields/Implementations/TextareaField.php
  packages/plugin/src/Integrations/SpamBlocking/Emails/BlockEmailAddresses.php
  packages/plugin/src/Integrations/SpamBlocking/Emails/README.md
  packages/plugin/src/Integrations/SpamBlocking/Emails/icon.svg
  packages/plugin/src/Integrations/SpamBlocking/IpAddresses/BlockIpAddresses.php
  packages/plugin/src/Integrations/SpamBlocking/IpAddresses/README.md
  packages/plugin/src/Integrations/SpamBlocking/IpAddresses/icon.svg
  packages/plugin/src/Integrations/SpamBlocking/Keywords/BlockKeywords.php
  packages/plugin/src/Integrations/SpamBlocking/Keywords/README.md
  packages/plugin/src/Integrations/SpamBlocking/Keywords/icon.svg
  packages/plugin/src/Integrations/SpamBlocking/SpamBlockingBundle.php
  packages/plugin/src/Library/Helpers/IpUtils.php
  packages/plugin/src/Library/Helpers/StringHelper.php
  packages/plugin/src/Library/Integrations/IntegrationInterface.php
  packages/plugin/src/Library/Integrations/Types/SpamBlocking/SpamBlockingIntegration.php
  packages/plugin/src/Library/Integrations/Types/SpamBlocking/SpamBlockingIntegrationInterface.php
  packages/plugin/src/Models/Settings.php
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
  packages/plugin/src/Resources/js/client/vendor.js.LICENSE.txt
  packages/plugin/src/Services/Integrations/IntegrationsService.php
  packages/plugin/src/Services/SettingsService.php
  packages/plugin/src/Tests/Library/Helpers/StringHelperTest.php
  packages/plugin/src/controllers/integrations/IntegrationsController.php
  packages/plugin/src/migrations/m240619_111214_GenerateSpamBlockIntegrations.php
  packages/plugin/src/templates/settings/_spam.twig
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature

#1360 [SFT-830]: Post Forwarding file attachments
  packages/plugin/src/Integrations/Single/PostForwarding/EventListeners/PostForwardingTrigger.php
  packages/plugin/src/Integrations/Single/PostForwarding/PostForwarding.php
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: feature

#1365 [SFT-1194]: Tooltip library replacement
  packages/plugin/src/Resources/css/front-end/fields/drag-and-drop-file.css
  packages/plugin/src/Resources/css/front-end/plugin/freeform.css
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/client/vendor.js
  packages/plugin/src/Resources/js/client/vendor.js.LICENSE.txt
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/scripts/src/lib/plugin/handlers/fields/drag-and-drop/error-handling.ts
  packages/styles/src/front-end/fields/drag-and-drop-file.scss
Labels: fix

#1371 [SFT-1220][#1355]: Row order inconsistencies in builder
  packages/client/src/app/pages/forms/edit/store/slices/layout/rows/index.ts
  packages/plugin/src/Resources/css/front-end/fields/drag-and-drop-file.css
  packages/plugin/src/Resources/css/front-end/plugin/freeform.css
  packages/plugin/src/Resources/js/client/client.js
  packages/plugin/src/Resources/js/scripts/front-end/plugin/freeform.js
  packages/scripts/src/lib/plugin/handlers/fields/drag-and-drop/error-handling.ts
  packages/styles/src/front-end/fields/drag-and-drop-file.scss
Labels: fix

#1369 [SFT-1211]: DateTime field validation issues with native html types
  packages/plugin/src/Bundles/Fields/Validation/DateValidation.php
  packages/plugin/src/Fields/Implementations/Pro/DatetimeField.php
  packages/plugin/src/Resources/js/scripts/front-end/payments/stripe/elements.js
Labels: fix

#1376 [SFT-1219]: Integration and Notification jobs breaking when no submissions stored
  packages/plugin/src/Bundles/Form/Context/Request/DefaultValuesContext.php
  packages/plugin/src/Bundles/Notifications/NotificationsBundle.php
  packages/plugin/src/Bundles/Notifications/SendListeners/AdminNotifications.php
  packages/plugin/src/Bundles/Notifications/SendListeners/ConditionalNotifications.php
  packages/plugin/src/Bundles/Notifications/SendListeners/DynamicRecipients.php
  packages/plugin/src/Bundles/Notifications/SendListeners/DynamicTemplateRecipients.php
  packages/plugin/src/Bundles/Notifications/SendListeners/EmailRecipientNotifications.php
  packages/plugin/src/Elements/Actions/Pro/ResendNotificationsAction.php
  packages/plugin/src/Elements/Submission.php
  packages/plugin/src/Events/Forms/SendNotificationsEvent.php
  packages/plugin/src/Form/Form.php
  packages/plugin/src/Integrations/CRM/CrmBundle.php
  packages/plugin/src/Integrations/EmailMarketing/EmailMarketingBundle.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/GoogleSheetsBundle.php
  packages/plugin/src/Jobs/ProcessEmailMarketingIntegrationsJob.php
  packages/plugin/src/Jobs/ProcessGoogleSheetsIntegrationsJob.php
  packages/plugin/src/Jobs/ProcessIntegrationsJob.php
  packages/plugin/src/Jobs/SendNotificationsJob.php
  packages/plugin/src/Library/Helpers/TwigHelper.php
  packages/plugin/src/Library/Mailing/MailHandlerInterface.php
  packages/plugin/src/Services/Integrations/IntegrationsService.php
  packages/plugin/src/Services/MailerService.php
  packages/plugin/src/controllers/notifications/SenderController.php
  packages/plugin/src/translations/en-US/freeform.php
  packages/plugin/src/translations/nl/freeform.php
Labels: fix

#1381 [SFT-1221][#1370]: OAuth2.0 token refreshing
  packages/plugin/src/Bundles/Integrations/OAuth/OAuth2RefreshTokenBundle.php
  packages/plugin/src/Integrations/CRM/Pardot/BasePardotIntegration.php
  packages/plugin/src/Integrations/CRM/Salesforce/BaseSalesforceIntegration.php
  packages/plugin/src/Integrations/Other/Google/GoogleSheets/BaseGoogleSheetsIntegration.php
  packages/plugin/src/Library/Integrations/OAuth/OAuth2IssuedAtMilliseconds.php
Labels: fix
